defmodule Todos.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:user_tag_orders, [:user_id])

    drop_if_exists index(:todos, [:due_date])

    drop_if_exists index(:todos, [:state])

    drop_if_exists index(:todos, [:user_id])

    drop_if_exists index(:todo_tags, [:tag_id])

    drop_if_exists index(:todo_tags, [:todo_id])

    drop_if_exists index(:todo_assignees, [:todo_id])

    drop_if_exists index(:subtasks, [:todo_id])
  end

  def down do
    create index(:subtasks, [:todo_id])

    create index(:todo_assignees, [:todo_id])

    create index(:todo_tags, [:todo_id])

    create index(:todo_tags, [:tag_id])

    create index(:todos, [:user_id])

    create index(:todos, [:state])

    create index(:todos, [:due_date])

    create index(:user_tag_orders, [:user_id])
  end
end
