defmodule Todos.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext
      add :hashed_password, :text
      add :tailscale_login, :text
      add :tailscale_name, :text
      add :tailscale_user, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index", nulls_distinct: false)

    create unique_index(:users, [:tailscale_login],
             name: "users_unique_tailscale_login_index",
             nulls_distinct: false
           )

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:todos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :state, :text, null: false, default: "inbox"
      add :priority, :text, default: "medium"
      add :due_date, :date
      add :completed_at, :utc_datetime
      add :pinned_to_today, :boolean, null: false, default: false
      add :waiting_on, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "todos_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recurring_pattern_id, :uuid
      add :archived_at, :utc_datetime_usec
    end

    create table(:todo_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :todo_id,
          references(:todos,
            column: :id,
            name: "todo_tags_todo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :tag_id, :uuid, null: false, primary_key: true
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:todo_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "todo_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tags) do
      add :name, :text, null: false
      add :color, :text, default: "#6366f1"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:name], name: "tags_unique_name_index")

    create table(:subtasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :completed, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :todo_id,
          references(:todos,
            column: :id,
            name: "subtasks_todo_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end

    create table(:recurring_patterns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:todos) do
      modify :recurring_pattern_id,
             references(:recurring_patterns,
               column: :id,
               name: "todos_recurring_pattern_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:recurring_patterns) do
      add :frequency, :text, null: false
      add :interval, :bigint, null: false, default: 1
      add :days_of_week, {:array, :bigint}
      add :day_of_month, :bigint
      add :last_generated_at, :utc_datetime
      add :ends_at, :date
      add :paused, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:recurring_patterns) do
      remove :updated_at
      remove :inserted_at
      remove :paused
      remove :ends_at
      remove :last_generated_at
      remove :day_of_month
      remove :days_of_week
      remove :interval
      remove :frequency
    end

    drop constraint(:todos, "todos_recurring_pattern_id_fkey")

    alter table(:todos) do
      modify :recurring_pattern_id, :uuid
    end

    drop table(:recurring_patterns)

    drop constraint(:subtasks, "subtasks_todo_id_fkey")

    drop table(:subtasks)

    drop_if_exists unique_index(:tags, [:name], name: "tags_unique_name_index")

    alter table(:tags) do
      remove :updated_at
      remove :inserted_at
      remove :color
      remove :name
    end

    drop constraint(:todo_tags, "todo_tags_tag_id_fkey")

    alter table(:todo_tags) do
      modify :tag_id, :uuid
    end

    drop table(:tags)

    drop constraint(:todo_tags, "todo_tags_todo_id_fkey")

    drop table(:todo_tags)

    drop constraint(:todos, "todos_user_id_fkey")

    drop table(:todos)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:tailscale_login],
                     name: "users_unique_tailscale_login_index"
                   )

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
