defmodule Todos.Repo.Migrations.AddCascadeDeleteToTodoTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:todo_tags, "todo_tags_tag_id_fkey")

    drop constraint(:todo_tags, "todo_tags_todo_id_fkey")

    alter table(:todo_tags) do
      modify :todo_id,
             references(:todos,
               column: :id,
               name: "todo_tags_todo_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               name: "todo_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:todo_tags, "todo_tags_todo_id_fkey")

    drop constraint(:todo_tags, "todo_tags_tag_id_fkey")

    alter table(:todo_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "todo_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :todo_id,
             references(:todos,
               column: :id,
               name: "todo_tags_todo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
