defmodule Todos.Repo.Migrations.AddPlanBoards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plan_boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :cards, {:array, :map}, null: false, default: []
      add :connections, {:array, :map}, null: false, default: []
      add :viewport_x, :float, null: false, default: 0.0
      add :viewport_y, :float, null: false, default: 0.0
      add :zoom, :float, null: false, default: 1.0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "plan_boards_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:plan_boards, "plan_boards_user_id_fkey")

    drop table(:plan_boards)
  end
end
