defmodule Todos.Repo.Migrations.AddCompletedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :completed_by_id,
          references(:users,
            column: :id,
            name: "todos_completed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:todos, "todos_completed_by_id_fkey")

    alter table(:todos) do
      remove :completed_by_id
    end
  end
end
