defmodule Todos.Repo.Migrations.AddPreviousStateToTodos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :previous_state, :text
    end
  end

  def down do
    alter table(:todos) do
      remove :previous_state
    end
  end
end
