defmodule Todos.Repo.Migrations.AddUserTagOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_tag_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_tag_orders_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "user_tag_orders_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:user_tag_orders, [:user_id, :tag_id],
             name: "user_tag_orders_unique_user_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_tag_orders, [:user_id, :tag_id],
                     name: "user_tag_orders_unique_user_tag_index"
                   )

    drop constraint(:user_tag_orders, "user_tag_orders_user_id_fkey")

    drop constraint(:user_tag_orders, "user_tag_orders_tag_id_fkey")

    drop table(:user_tag_orders)
  end
end
